#include <GLFW/glfw3.h>
#include <iostream>
#include <vector>
#include <cmath>

const int WIDTH = 640;
const int HEIGHT = 480;

// define our structs
// a 3d vector struct, generated by AI, to help with raytracing calculations
// implements GLM-like vector operations for convenience
struct Vec3 {
    float x, y, z;
    Vec3 operator+(const Vec3& v) const { return {x + v.x, y + v.y, z + v.z}; }
    Vec3 operator-(const Vec3& v) const { return {x - v.x, y - v.y, z - v.z}; }
    Vec3 operator*(float s) const { return {x * s, y * s, z * s}; }
    
    float dot(const Vec3& v) const { return x * v.x + y * v.y + z * v.z; }
    
    Vec3 normalize() const {
        float mg = std::sqrt(x * x + y * y + z * z);
        return {x / mg, y / mg, z / mg};
    }
};

inline Vec3 operator*(float s, const Vec3& v) { return v * s; }

// a ray struct, generated by AI, to represent rays in our raytracer
struct Ray {
    Vec3 origin;
    Vec3 direction;
    Vec3 at(float t) const { return origin + (direction * t); }
};

// define a simple class that we extend off
// we expose doesIntersect so each extended class can write their own intersection logic
// so obv we can determine if we intersect with a ray or not
class Hittable {
    public:
        Vec3 center;

        Hittable(const Vec3& c) : center(c) {}
        virtual ~Hittable() {}
        virtual float getIntersection(const Ray& ray) const = 0;
        virtual Vec3 getNormal(const Vec3& hitPoint) const = 0;
};

// class for a sphere
class Sphere : public Hittable {
    public:
        float radius;

        Sphere(const Vec3& c, float r) : Hittable(c), radius(r) {}

        // intersection is based on quadratic formula based on radius
        float getIntersection(const Ray& ray) const override {
            Vec3 oc = ray.origin - center;
            float a = ray.direction.dot(ray.direction);
            float b = 2.0f * oc.dot(ray.direction);
            float c = oc.dot(oc) - radius * radius;
            float quadratic = b * b - 4 * a * c;

            if (quadratic < 0) return -1.0f;

            float t = (-b - std::sqrt(quadratic)) / (2.0f * a);
            return (t > 0) ? t : -1.0f; 
        }

        Vec3 getNormal(const Vec3& hitPoint) const override {
            return (hitPoint - center).normalize();
        }
};

// a square!
class Square : public Hittable {
    public:
        float sideLength;

        Square(const Vec3& c, float s) : Hittable(c), sideLength(s) {}

        // ok so intersection with a square is actually more complicated than a sphere
        float getIntersection(const Ray& ray) const override {
            // if parallel to the plane, we won't hit it
            if (std::abs(ray.direction.y) < 1e-6) return -1.0f;

            // calculate intersection
            float t = (center.y - ray.origin.y) / ray.direction.y;
            if (t < 0) return -1.0f; 

            Vec3 hitPoint = ray.at(t);
            float h = sideLength / 2.0f;

            // within bounds on the plane for the square
            if (hitPoint.x >= center.x - h && hitPoint.x <= center.x + h &&
                hitPoint.z >= center.z - h && hitPoint.z <= center.z + h) {
                return t;
            }

            // didn't hit
            return -1.0f;
        }

        // sqare normal now points up. honestly this sohuld be called floor but i don't care
        Vec3 getNormal(const Vec3& hitPoint) const override {
            return {0, 1, 0}; 
        }
};

// we define a list of hittable objects in our scene for the sphere animation
std::vector<Hittable*> sceneObjects = {
    // a MASSIVE square floor
    new Square({0.0f, -1.0f, -5.0f}, 100.0f), 

    // da sphere in the middle
    new Sphere({0.0f, 0.0f, -5.0f}, 1.0f),

    // the one in orbit
    new Sphere({0.0f, 0.0f, -5.0f}, 0.5f)
};

std::vector<float> raytraceScene(float time) {
    // create a buffer to hold the color value of each ray-traced pixel
    std::vector<float> pixels(WIDTH * HEIGHT * 3);

    // logic to rotate the second sphere around the first one
    if (sceneObjects.size() >= 3) {
        float orbitRadius = 2.0f;

        sceneObjects[2]->center.x = sceneObjects[1]->center.x + std::sin(time) * orbitRadius;
        sceneObjects[2]->center.z = sceneObjects[1]->center.z + std::cos(time) * orbitRadius;
        sceneObjects[2]->center.y = std::sin(time * 0.5f) * 0.5f; 
    }

    // loop over every pixel within the scene
    for (int y = 0; y < HEIGHT; y++) {
            for (int x = 0; x < WIDTH; x++) {
                // create a ray from the camera which goes through the pixel
                // convert to a coordinate system (UV mapping)
                float u = (float)x / WIDTH * 2.0f - 1.0f;
                float v = (float)y / HEIGHT * 2.0f - 1.0f;
                float aspect = (float)WIDTH / HEIGHT;
                u *= aspect; 

                Ray ray = {{0, 0, 0}, {u, v, -1.0f}};

                // check if the ray intersects with any object in the scene
                // this gets complicated because we must ensure we hit the closest object
                float closest_t = 1e30f; // infinity
                Hittable* closest_obj = nullptr;

                for (const auto& obj : sceneObjects) {
                    float t = obj->getIntersection(ray);
                    if (t > 0.0f && t < closest_t) {
                        closest_t = t;
                        closest_obj = obj;
                    }
                }   

                // if we hit an object, we calculate the color based on the normal at the hit point
                // so we can have a cool lil look to the sphere
                int idx = (y * WIDTH + x) * 3;
                if (closest_obj) {
                    // find the point where the ray hits the object
                    Vec3 hit_point = ray.at(closest_t);

                    // calculate the vector normal at the hit point
                    Vec3 normal = closest_obj->getNormal(hit_point);

                    // some seperate logic for the checkerboard pattern on the floor
                    // if the closest object (obj 0) is floor
                    if(closest_obj == sceneObjects[0]) {
                        // compute a check variable based on the x & z positions of the hit point
                        int check = (int)(std::floor(hit_point.x * 1.0f)) + (int)(std::floor(hit_point.z * 1.0f));
                        
                        // use the check to swap two colors for the checkerboard pattern
                        if (check % 2 == 0) {
                            pixels[idx] = 1.0f; pixels[idx+1] = 1.0f; pixels[idx+2] = 0.0f;
                        } else {
                            pixels[idx] = 1.0f; pixels[idx+1] = 0.0f; pixels[idx+2] = 0.0f;
                        }
                    } else {
                        // generate the RGB values based on the normal
                        pixels[idx] = (normal.x + 1.0f) * 0.5f; // red
                        pixels[idx + 1] = (normal.y + 1.0f) * 0.5f; // green
                        pixels[idx + 2] = (normal.z + 1.0f) * 0.5f; // blue!
                    }
                } else {
                    // if not hit, we set the pixel color to a background color (gray)
                    pixels[idx] = 0.1f; pixels[idx+1] = 0.1f; pixels[idx+2] = 0.1f;
                }
            }
        }

    return pixels;
}

int main() {
    if (!glfwInit()) return -1;

    GLFWwindow* window = glfwCreateWindow(WIDTH, HEIGHT, "Project5", NULL, NULL);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    while (!glfwWindowShouldClose(window)) {
        glClear(GL_COLOR_BUFFER_BIT);

        glViewport(0, 0, WIDTH, HEIGHT);

        float time = glfwGetTime();
        auto rayTracedPixels = raytraceScene(time);

        glDrawPixels(WIDTH, HEIGHT, GL_RGB, GL_FLOAT, rayTracedPixels.data());

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}