#include <GLFW/glfw3.h>
#include <iostream>
#include <vector>
#include <cmath>

const int WIDTH = 640;
const int HEIGHT = 480;

// define our structs
// a 3d vector struct, generated by AI, to help with raytracing calculations
// implements GLM-like vector operations for convenience
struct Vec3 {
    float x, y, z;
    Vec3 operator+(const Vec3& v) const { return {x + v.x, y + v.y, z + v.z}; }
    Vec3 operator-(const Vec3& v) const { return {x - v.x, y - v.y, z - v.z}; }
    Vec3 operator*(float s) const { return {x * s, y * s, z * s}; }
    
    float dot(const Vec3& v) const { return x * v.x + y * v.y + z * v.z; }
    
    Vec3 normalize() const {
        float mg = std::sqrt(x * x + y * y + z * z);
        return {x / mg, y / mg, z / mg};
    }
};

// a ray struct, generated by AI, to represent rays in our raytracer
struct Ray {
    Vec3 origin;
    Vec3 direction;
    Vec3 at(float t) const { return origin + (direction * t); }
};

// define a simple class that we extend off
// we expose doesIntersect so each extended class can write their own intersection logic
// so obv we can determine if we intersect with a ray or not
class Hittable {
    public:
        virtual float getIntersection(const Ray& ray) const = 0;
        virtual Vec3 getNormal(const Vec3& hitPoint) const = 0;
};

// class for a sphere
class Sphere : public Hittable {
    public:
        Vec3 center;
        float radius;

        Sphere(const Vec3& c, float r) : center(c), radius(r) {}

        // intersection is based on quadratic formula based on radius
        float getIntersection(const Ray& ray) const override {
            Vec3 oc = ray.origin - center;
            float a = ray.direction.dot(ray.direction);
            float b = 2.0f * oc.dot(ray.direction);
            float c = oc.dot(oc) - radius * radius;
            float quadratic = b * b - 4 * a * c;

            if (quadratic < 0) return -1.0f;

            float t = (-b - std::sqrt(quadratic)) / (2.0f * a);
            return (t > 0) ? t : -1.0f; 
        }

        Vec3 getNormal(const Vec3& hitPoint) const override {
            return (hitPoint - center).normalize();
        }
};

// a square!
class Square : public Hittable {
    public:
        Vec3 center;
        float sideLength;

        Square(const Vec3& c, float s) : center(c), sideLength(s) {}

        // ok so intersection with a square is actually more complicated than a sphere
        float getIntersection(const Ray& ray) const override {
            // if the ray is parallel to the plane of the square, we clearly don't intersect
            if (std::abs(ray.direction.z) < 1e-6) return -1.0f;

            // calculate the distance to the plane of the square
            // if the ray is pointing away from the plane, we also don't intersect
            float t = (center.z - ray.origin.z) / ray.direction.z;
            if (t < 0) return -1.0f; 

            // now we find our hit point on the plane that the square lines on
            Vec3 hitPoint = ray.at(t);

            // we must check if the ray intersects within the bounds of the square
            float halfSide = sideLength / 2.0f;
            if (hitPoint.x >= center.x - halfSide && hitPoint.x <= center.x + halfSide &&
                hitPoint.y >= center.y - halfSide && hitPoint.y <= center.y + halfSide) {
                return t;
            }

            // since we didn't hit within the bounds of the square, we don't intersect
            return -1.0f;
        }

        Vec3 getNormal(const Vec3& hitPoint) const override {
            return {0, 0, 1};
        }
};

// we define a list of hittable objects in our scene
std::vector<Hittable*> sceneObjects = {
    new Sphere({-1.0f, 0, -1.5f}, 0.5f),
    new Square({1.0f, 0, -2.0f}, 1.0f)
    //new Sphere({0.0f, 0, -3.0f}, 1.0f)
};

std::vector<float> raytraceScene() {
    // create a buffer to hold the color value of each ray-traced pixel
    std::vector<float> pixels(WIDTH * HEIGHT * 3);

    // loop over every pixel within the scene
    for (int y = 0; y < HEIGHT; y++) {
            for (int x = 0; x < WIDTH; x++) {
                // create a ray from the camera which goes through the pixel
                // convert to a coordinate system (UV mapping)
                float u = (float)x / WIDTH * 2.0f - 1.0f;
                float v = (float)y / HEIGHT * 2.0f - 1.0f;
                float aspect = (float)WIDTH / HEIGHT;
                u *= aspect; 

                Ray ray = {{0, 0, 0}, {u, v, -1.0f}};

                // check if the ray intersects with any object in the scene
                // this gets complicated because we must ensure we hit the closest object
                float closest_t = 1e30f; // infinity
                Hittable* closest_obj = nullptr;

                for (const auto& obj : sceneObjects) {
                float t = obj->getIntersection(ray);
                    if (t > 0.0f && t < closest_t) {
                        closest_t = t;
                        closest_obj = obj;
                    }
                }

                // if we hit an object, we calculate the color based on the normal at the hit point
                // so we can have a cool lil look to the sphere
                int idx = (y * WIDTH + x) * 3;
                if (closest_obj) {
                    // find the point where the ray hits the object
                    Vec3 hit_point = ray.at(closest_t);

                    // calculate the vector normal at the hit point
                    Vec3 normal = closest_obj->getNormal(hit_point);
                    
                    // generate the RGB values based on the normal
                    pixels[idx] = (normal.x + 1.0f) * 0.5f; // red
                    pixels[idx + 1] = (normal.y + 1.0f) * 0.5f; // green
                    pixels[idx + 2] = (normal.z + 1.0f) * 0.5f; // blue!
                } else {
                    // if not hit, we set the pixel color to a background color (gray)
                    pixels[idx] = 0.1f; pixels[idx+1] = 0.1f; pixels[idx+2] = 0.1f;
                }
            }
        }

    return pixels;
}

int main() {
    if (!glfwInit()) return -1;

    GLFWwindow* window = glfwCreateWindow(WIDTH, HEIGHT, "Project5", NULL, NULL);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    while (!glfwWindowShouldClose(window)) {
        glClear(GL_COLOR_BUFFER_BIT);

        glViewport(0, 0, WIDTH, HEIGHT);

        auto rayTracedPixels = raytraceScene();

        glDrawPixels(WIDTH, HEIGHT, GL_RGB, GL_FLOAT, rayTracedPixels.data());

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}